[ci/cd] version

diff --git a/.github/workflows/deploystaging.yml b/.github/workflows/deploystaging.yml
--- a/.github/workflows/deploystaging.yml
+++ b/.github/workflows/deploystaging.yml
@@ -55,9 +55,11 @@ jobs:
         env:
           ORGANIZATION: alterra.id # example
           APP_NAME: rrs-web # example
+
+        # VERSION=$(git describe --tags --abbrev=0) # will fail if never tagged
         run: |
-          set -e
-          VERSION=$(git describe --tags --abbrev=0) # will fail if never tagged
+          set -e          
+          VERSION=$(grep "version" ./package.json | grep -Eo '[0-9]+(\.[0-9]+){2}(-[^"]+)?')"
           DOCKER_IMAGE=${ORGANIZATION}/${APP_NAME}
 
           if [[ ${GITHUB_REF#refs/heads/} == 'master' ]]; then # Check by branch name
