HOTI-161 deploy staging n prod remove auto deploy master

diff --git a/.github/workflows/deployproduction.yml b/.github/workflows/deployproduction.yml
--- a/.github/workflows/deployproduction.yml
+++ b/.github/workflows/deployproduction.yml
@@ -104,92 +104,92 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-  docker-build:
-    name: Docker Build
+  # docker-build:
+  #   name: Docker Build
 
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-    # Make sure the code is tested before build docker
-    needs: sonarcloud
-    if: github.event_name == 'push' && success()
+  #   # The type of runner that the job will run on
+  #   runs-on: ubuntu-latest
+  #   # Make sure the code is tested before build docker
+  #   needs: sonarcloud
+  #   if: github.event_name == 'push' && success()
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
 
-      # Create and gather metadata
-      - name: Get Repo metadata
-        id: repo
-        uses: actions/github-script@v3
-        with:
-          script: |
-            const repo = await github.repos.get(context.repo)
-            return repo.data
+  #     # Create and gather metadata
+  #     - name: Get Repo metadata
+  #       id: repo
+  #       uses: actions/github-script@v3
+  #       with:
+  #         script: |
+  #           const repo = await github.repos.get(context.repo)
+  #           return repo.data
 
-      - name: Prepare Version and Tag
-        id: prep
-        env:
-          ORGANIZATION: sepulsa # example
-          APP_NAME: rrs-web # example
-        # VERSION=$(git describe --tags --abbrev=0) # will fail if never tagged
-        working-directory: ./src
-        run: |
-          set -e          
-          VERSION=$(grep "version" ./package.json | grep -Eo '[0-9]+(\.[0-9]+){2}(-[^"]+)?')
-          DOCKER_IMAGE=${ORGANIZATION}/${APP_NAME}
-          TAGS=${DOCKER_IMAGE}:$VERSION-dev-${GITHUB_SHA::8}
-          echo ::set-output name=version::${VERSION}
-          echo ::set-output name=tags::${TAGS}
-          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
+  #     - name: Prepare Version and Tag
+  #       id: prep
+  #       env:
+  #         ORGANIZATION: sepulsa # example
+  #         APP_NAME: rrs-web # example
+  #       # VERSION=$(git describe --tags --abbrev=0) # will fail if never tagged
+  #       working-directory: ./src
+  #       run: |
+  #         set -e          
+  #         VERSION=$(grep "version" ./package.json | grep -Eo '[0-9]+(\.[0-9]+){2}(-[^"]+)?')
+  #         DOCKER_IMAGE=${ORGANIZATION}/${APP_NAME}
+  #         TAGS=${DOCKER_IMAGE}:$VERSION-dev-${GITHUB_SHA::8}
+  #         echo ::set-output name=version::${VERSION}
+  #         echo ::set-output name=tags::${TAGS}
+  #         echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
 
-      # Deploy to docker registry
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      - name: Cache Docker layers
-        uses: actions/cache@v2
-        with:
-          path: /tmp/.buildx-main-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-
-      - name: Login to Docker Registry
-        # if: github.event_name == 'release'
-        uses: docker/login-action@v1
-        with:
-          #registry: ${{ secrets.DOCKER_REGISTRY_DOCKERHUB }}
-          username: ${{ secrets.DOCKER_USERNAME_DOCKERHUB }}
-          password: ${{ secrets.DOCKER_PASSWORD_DOCKERHUB }}
+  #     # Deploy to docker registry
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v1
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v1
+  #     - name: Cache Docker layers
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: /tmp/.buildx-main-cache
+  #         key: ${{ runner.os }}-buildx-${{ github.sha }}
+  #         restore-keys: |
+  #           ${{ runner.os }}-buildx-
+  #     - name: Login to Docker Registry
+  #       # if: github.event_name == 'release'
+  #       uses: docker/login-action@v1
+  #       with:
+  #         #registry: ${{ secrets.DOCKER_REGISTRY_DOCKERHUB }}
+  #         username: ${{ secrets.DOCKER_USERNAME_DOCKERHUB }}
+  #         password: ${{ secrets.DOCKER_PASSWORD_DOCKERHUB }}
 
-      - name: Build and push
-        id: docker_build
-        uses: docker/build-push-action@v2
-        with:
-          context: src
-          file: src/Dockerfile
-          platforms: linux/amd64
-          # push: ${{ github.event_name == 'release' }}
-          push: true
-          # tags: ${{ secrets.DOCKER_REGISTRY_DOCKERHUB }}/${{ steps.prep.outputs.tags }}
-          #tags: ${{ steps.prep.outputs.tags }}
-          tags: sepulsa/relative-ranking-system:rrs-web-${{ github.sha }}
-          cache-from: type=local,src=/tmp/.buildx-main-cache
-          cache-to: type=local,dest=/tmp/.buildx-main-cache
-          labels: |
-            org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
-            org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
-            org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
-            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
-            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
-            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
-            org.opencontainers.image.revision=${{ github.sha }}
-            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
+  #     - name: Build and push
+  #       id: docker_build
+  #       uses: docker/build-push-action@v2
+  #       with:
+  #         context: src
+  #         file: src/Dockerfile
+  #         platforms: linux/amd64
+  #         # push: ${{ github.event_name == 'release' }}
+  #         push: true
+  #         # tags: ${{ secrets.DOCKER_REGISTRY_DOCKERHUB }}/${{ steps.prep.outputs.tags }}
+  #         #tags: ${{ steps.prep.outputs.tags }}
+  #         tags: sepulsa/relative-ranking-system:rrs-web-${{ github.sha }}
+  #         cache-from: type=local,src=/tmp/.buildx-main-cache
+  #         cache-to: type=local,dest=/tmp/.buildx-main-cache
+  #         labels: |
+  #           org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
+  #           org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
+  #           org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
+  #           org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
+  #           org.opencontainers.image.version=${{ steps.prep.outputs.version }}
+  #           org.opencontainers.image.created=${{ steps.prep.outputs.created }}
+  #           org.opencontainers.image.revision=${{ github.sha }}
+  #           org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
 
-  deploy-staging:
+  # deploy-staging:
     name: Deploy Staging
     runs-on: ubuntu-latest
     needs: [docker-build]
